# Generated by Django 4.2.5 on 2023-09-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('studentID', models.CharField(max_length=32)),
                ('group', models.CharField(max_length=32)),
                ('grade', models.CharField(max_length=32)),
            ],
        ),
    ]
